### PR TITLE
add label, and show label instead of url on ribbon, and ribbon position

### PR DESCRIPTION
**Pull request by loguilhem**
thanks for your work, i need an extension like that on firefox !
I also needed to add label to the ribbon (DEV, INTE, PROD... and why not something else) and also be able to choose ribbon position.

I made a little change in the hide/show empty message, i let you judge.

If your ok with this feature, can you review the PR ? I will correct mistakes and "coding styles" if necessary of course :) .

### CODE REVIEW

**Comment by XjSv** [comment]
Great work, thank you. 
I will test everything before packaging it up for upload to addons.mozilla.org.

**Comment by XjSv** [comment]
I am planing on merging this branch and fixing the UI issues. Some things that I notices:
* The UI does not look decent, including the styles for the `select` which look different than the rest.
* The `select` `options` could use some human readable labels such as: Top Right and Top Left instead of top-right and top-left.
* The same 2 issues above are also relevant to the inline editing. 

I am not a UI designer but here is my idea.

Example

The idea is to make the inline editing part look the same as that.

**Note:** If you want I can commit whatever I have done so far for you to take a look.

**Comment by loguilhem** [comment]
You are right, i didnt't take time to make it beautiful (to me as long as it works, i'm ok with it :p ). Sure you can commit so i will take a look et update my branch.

**Comment by XjSv** [comment]
I have created https://github.com/loguilhem/environment-marker/pull/2 in your repository.

**Comment by XjSv** [comment]
I also need to fix the inline editing form unless you want to take it from here and fix that last part?

**Comment by loguilhem** [comment]
It is like you want. I will do it tomorrow if you do not have time.

Also, maybe a little change in the description would be clever : "Adds 
a color marker (ribbon) to the top left of the page depending if the 
URL contains a given string (e.g. 'http://dev-', 'http://prod-'). It 
uses JavaScript's indexOf to determine if the string is found"

-> i do not understant the part "if the URL contains a given string 
(e.g. 'http://dev-', 'http://prod-'" ... maybe we should delete this 
and just write :
Adds a color marker (ribbon) to the page depending on the URL ?
--
Guilhem VILLARROYA
06 38 53 38 79
Alteragile / Développement Web & Formations
www.alteragile.com

**Comment by loguilhem** [comment]
Hello. I just updated the PR, forms are now "inline-style". I didn't change the style of the arrow, i tested with this : https://codepen.io/vkjgr/pen/VYMeXp 
it looks great for the "new form" but not for the "edit form" so i prefer to keep the native style.

**Comment by XjSv** [comment]
Thanks for the edit. I was just able to get to it today.

**Comment by XjSv** [comment]
> 
> It is like you want. I will do it tomorrow if you do not have time. Also, maybe a little change in the description would be clever : "Adds a color marker (ribbon) to the top left of the page depending if the URL contains a given string (e.g. 'http://dev-', 'http://prod-'). It uses JavaScript's indexOf to determine if the string is found" -> i do not understant the part "if the URL contains a given string (e.g. 'http://dev-', 'http://prod-'" ... maybe we should delete this and just write : Adds a color marker (ribbon) to the page depending on the URL ? Le mar. 28 avril 2020 à 15:41, Armand Tresova <notifications@github.com> a écrit :
> […](#)

I just realized that I did not address your description question. I have opened issue https://github.com/XjSv/environment-marker/issues/5 to track this.

**Pull request merged**
