### PR TITLE
Alpha v2.5 Opacity Control, Font, Font Size, New Options/Settings Page & Performance Improvements

### PR DESCRIPTION
**Pull request by XjSv**
### Description
Alpha v2.5 Opacity Control, Font, Font Size, New Options/Settings Page & Performance Improvements

- Redesigned the Options/Settings page.
- Added opacity control to the color picker.
- Added the option to change the ribbons font globally. Font come from Google Fonts.
- Added font size to the individual ribbons. The font size can be controlled individually unlike the font family which is global.
- Performance improvements: Fixed bug where the updateContent() function was called multiple times during the life cycle of a tab. It should only be executed when the page completes loading.
- Other general performance improvements.
- Accessibility (A11Y) improvements.
- Updated documentation and screenshots.

### Checklist
Please check if your PR fulfills the following requirements:
- [x] Tested in Firefox and Chrome
- [x] No errors or warnings in the console
- [x] Extended the README / documentation, if necessary
- [x] Extended language files (e.g. `_locales/en/messages.json`), if necessary
- [x] Updated the build script if neccessary

### CODE REVIEW

**Comment by Splaxi** [comment]
Can't wait to see these things make it out so I can use it. Thank you for taking the time to look at all my suggestions 🤘

**Comment by XjSv** [comment]
No problem, I am currently just testing the changes. I discovered a couple of CSS bugs due to the introduction of the font size. The new release will be out as soon as the bugs are fixed.

**Comment by Splaxi** [comment]
Just want to see if you can share an update for this feature? 🤞

**Comment by XjSv** [comment]
Just a follow up update. The release is pretty much ready to go. I'm just waiting on an answer back from the Opera addons Moderators regarding a question about minified files. Apparently they had an issue with files being minified even though this is an open source project.

**Comment by Splaxi** [comment]
You rock 🤘

**Comment by XjSv** [comment]
Hopefully with these changes #19 and #20 should be resolved.

**Comment by Splaxi** [comment]
Will the extension automatically update?

**Comment by XjSv** [comment]
> Will the extension automatically update?

Yes it should. It has been approved for Firefox, Chrome and Edge. No word yet from Opera.

**Pull request merged**
